version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: chatbot
      MYSQL_USER: chatbotapp
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: java
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/chatbot
      SPRING_DATASOURCE_USERNAME: chatbotapp
      SPRING_DATASOURCE_PASSWORD: password123
      DB_SERVER: database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
